//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace beango.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindEntities1 : DbContext
    {
        public NorthwindEntities1()
            : base("name=NorthwindEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Auth> Auth { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<CustomerCustomerDemo> CustomerCustomerDemo { get; set; }
        public DbSet<CustomerDemographics> CustomerDemographics { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<EmployeeTerritories> EmployeeTerritories { get; set; }
        public DbSet<Order_Details> Order_Details { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<Regions> Regions { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<RoleAuth> RoleAuth { get; set; }
        public DbSet<Shippers> Shippers { get; set; }
        public DbSet<Suppliers> Suppliers { get; set; }
        public DbSet<Territories> Territories { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<Alphabetical_list_of_products> Alphabetical_list_of_products { get; set; }
        public DbSet<Current_Product_List> Current_Product_List { get; set; }
        public DbSet<Invoices> Invoices { get; set; }
        public DbSet<Order_Details_Extended> Order_Details_Extended { get; set; }
        public DbSet<Order_Subtotals> Order_Subtotals { get; set; }
        public DbSet<Orders_Qry> Orders_Qry { get; set; }
        public DbSet<Product_Sales_for_1997> Product_Sales_for_1997 { get; set; }
        public DbSet<Products_Above_Average_Price> Products_Above_Average_Price { get; set; }
        public DbSet<Products_by_Category> Products_by_Category { get; set; }
        public DbSet<Quarterly_Orders> Quarterly_Orders { get; set; }
        public DbSet<Sales_Totals_by_Amount> Sales_Totals_by_Amount { get; set; }
        public DbSet<Summary_of_Sales_by_Quarter> Summary_of_Sales_by_Quarter { get; set; }
        public DbSet<Summary_of_Sales_by_Year> Summary_of_Sales_by_Year { get; set; }
    }
}
