/* 创建索引 */
PRINT '开始创建索引'
GO
USE TestDB
GO
IF NOT EXISTS ( SELECT  1
                FROM    SYS.INDEXES
                WHERE   NAME = 'IX_EMPLOYEE_LASTNAME' ) 
    CREATE INDEX IX_EMPLOYEE_LASTNAME ON DBO.EMPLOYEE(LASTNAME, FIRSTNAME)
GO
IF NOT EXISTS ( SELECT  1
                FROM    SYS.INDEXES
                WHERE   NAME = 'IX_TIMECARD_EMPLOYEEID' ) 
    CREATE INDEX IX_TIMECARD_EMPLOYEEID ON DBO.TIMECARD(EMPLOYEEID)
GO